# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3042c1100317ae54648c61d9ef28e145dce9d40c193700afb32ab9cbeff6555ae376b6126bd505ac81b93114b2748abe5ccdb5285dd173f852a631f459f723

test:
  secret_key_base: 4157581d42c432ad36763aa912bc7acb9a582618939a5b023e2ef380dc542461c4308395952bc5e924dcfa424035588c06d9d8515d1a06cc41a27950b3f823fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
